### ISSUE TITLE
one file .htaccess its site dependent

### ISSUE THREAD

**Issue by hashimramzan** [WITPASS/witpass-wordpress-docker-image#6]
we should be able to customize .htaccess file like we are using php custom configuration

**Comment by KamranAzeem** [comment]
Is there a valid/compelling justification for this?

**Comment by hashimramzan** [comment]
yes as i said its always site dependents we may need rewrite many urls for seo purposes need to update to make some files auth based like this 
AuthUserFile /usr/local/etc/.htpasswd
AuthName "Name of Secure Area"
AuthType Basic
<Limit GET POST>
require valid-user
</Limit>

need to deflate, cache setting different css, js and font files 
Disabiling and enabiling driectory browsing

**Comment by KamranAzeem** [comment]
If we implement what you are suggesting, then we would move far away from the current way of working. In that case, I would suggest to move such websites to a different hosting solution, where you / developer / admin can have full control on everything the the site does. 
Please do not take this as my "non co-operation". The reason I am saying/suggesting this is because this soution was designed to avoid the mess which was there in Murtaza sb's websites. Also the idea was to just setup wordpress websites with least amount of maintenance where we are not dependent on (or on mercy of) the wordpress admin or server admin. If the needs have changed , or changed, then the solution needs to be changed accordingly to accomodate those changes.
We need to discuss this in a hangout meeting - in a noise/distraction free environment.

**Comment by hashimramzan** [comment]
a configuration file how can create a mess in code  i am asking these things only for seo and saying because i feel issue to complete a job if we cannot do let me know work around will follow that and yes lets discuss in meeting tomorrow please give me time i will availabel after 3 pm PKT tomorrow

**Comment by KamranAzeem** [comment]
Unfortunately, I cannot read without commas, and full stops. 

I would also suggest re-reading my reply above - i.e. "If we implement ...."

**Comment by KamranAzeem** [comment]
I have not received any further information on this one. If this needs attention, please fee-free to re-open this issue and provide more information.
